package com.dam.salesianostriana.ad.ejercicio01_kilo;

import java.util.List;

import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAJA".
 */
public class Caja {

    private Long id;
    private int numero;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CajaDao myDao;

    private List<Caja> cajas;

    public Caja() {
    }

    public Caja(Long id) {
        this.id = id;
    }

    public Caja(Long id, int numero) {
        this.id = id;
        this.numero = numero;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCajaDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Caja> getCajas() {
        if (cajas == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CajaDao targetDao = daoSession.getCajaDao();
            List<Caja> cajasNew = targetDao._queryCaja_Cajas(id);
            synchronized (this) {
                if(cajas == null) {
                    cajas = cajasNew;
                }
            }
        }
        return cajas;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetCajas() {
        cajas = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
