package com.dam.salesianostriana.ad.ejercicio01_kilo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alimentoDaoConfig;
    private final DaoConfig cajaDaoConfig;
    private final DaoConfig alimCajaDaoConfig;

    private final AlimentoDao alimentoDao;
    private final CajaDao cajaDao;
    private final AlimCajaDao alimCajaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alimentoDaoConfig = daoConfigMap.get(AlimentoDao.class).clone();
        alimentoDaoConfig.initIdentityScope(type);

        cajaDaoConfig = daoConfigMap.get(CajaDao.class).clone();
        cajaDaoConfig.initIdentityScope(type);

        alimCajaDaoConfig = daoConfigMap.get(AlimCajaDao.class).clone();
        alimCajaDaoConfig.initIdentityScope(type);

        alimentoDao = new AlimentoDao(alimentoDaoConfig, this);
        cajaDao = new CajaDao(cajaDaoConfig, this);
        alimCajaDao = new AlimCajaDao(alimCajaDaoConfig, this);

        registerDao(Alimento.class, alimentoDao);
        registerDao(Caja.class, cajaDao);
        registerDao(AlimCaja.class, alimCajaDao);
    }
    
    public void clear() {
        alimentoDaoConfig.getIdentityScope().clear();
        cajaDaoConfig.getIdentityScope().clear();
        alimCajaDaoConfig.getIdentityScope().clear();
    }

    public AlimentoDao getAlimentoDao() {
        return alimentoDao;
    }

    public CajaDao getCajaDao() {
        return cajaDao;
    }

    public AlimCajaDao getAlimCajaDao() {
        return alimCajaDao;
    }

}
