package ;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import .AlimCaja;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALIM_CAJA".
*/
public class AlimCajaDao extends AbstractDao<AlimCaja, Long> {

    public static final String TABLENAME = "ALIM_CAJA";

    /**
     * Properties of entity AlimCaja.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cantidad = new Property(1, int.class, "cantidad", false, "CANTIDAD");
        public final static Property Alimento_id = new Property(2, long.class, "alimento_id", false, "ALIMENTO_ID");
        public final static Property Caja_id = new Property(3, long.class, "caja_id", false, "CAJA_ID");
    };

    private DaoSession daoSession;


    public AlimCajaDao(DaoConfig config) {
        super(config);
    }
    
    public AlimCajaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALIM_CAJA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CANTIDAD\" INTEGER NOT NULL ," + // 1: cantidad
                "\"ALIMENTO_ID\" INTEGER NOT NULL ," + // 2: alimento_id
                "\"CAJA_ID\" INTEGER NOT NULL );"); // 3: caja_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALIM_CAJA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AlimCaja entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCantidad());
        stmt.bindLong(3, entity.getAlimento_id());
        stmt.bindLong(4, entity.getCaja_id());
    }

    @Override
    protected void attachEntity(AlimCaja entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AlimCaja readEntity(Cursor cursor, int offset) {
        AlimCaja entity = new AlimCaja( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // cantidad
            cursor.getLong(offset + 2), // alimento_id
            cursor.getLong(offset + 3) // caja_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AlimCaja entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCantidad(cursor.getInt(offset + 1));
        entity.setAlimento_id(cursor.getLong(offset + 2));
        entity.setCaja_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AlimCaja entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AlimCaja entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAlimentoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCajaDao().getAllColumns());
            builder.append(" FROM ALIM_CAJA T");
            builder.append(" LEFT JOIN ALIMENTO T0 ON T.\"ALIMENTO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN CAJA T1 ON T.\"CAJA_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AlimCaja loadCurrentDeep(Cursor cursor, boolean lock) {
        AlimCaja entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Alimento alimento = loadCurrentOther(daoSession.getAlimentoDao(), cursor, offset);
         if(alimento != null) {
            entity.setAlimento(alimento);
        }
        offset += daoSession.getAlimentoDao().getAllColumns().length;

        Caja caja = loadCurrentOther(daoSession.getCajaDao(), cursor, offset);
         if(caja != null) {
            entity.setCaja(caja);
        }

        return entity;    
    }

    public AlimCaja loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AlimCaja> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AlimCaja> list = new ArrayList<AlimCaja>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AlimCaja> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AlimCaja> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
